APP_NAME = 'PipelineExtractionLisnete'
API_KEY = "AQ6YIWxeByPe6kKE9xsq0Cb7o"
API_KEY_SECRET = "8u8tS0dYbnjUjdXa23wirqEDeeCIPHro0PBvxpMSuZtj4ziSkD"
ACCESS_TOKEN = "252882274-FHDrEZmlBHP4h74Eds3B2w5A0vLFvonHjJXZgHyj"
ACCESS_TOKEN_SECRET = "0TGn7yErRO36NCmYGYck3yPEmMEiTNS9eGOJnxT4hRjoG"
